[general]
annotation-size-factor = 0.6
initial-tool = "brush"
copy-command = "wl-copy"
output-filename = "~/Pictures/Screenshots/satty-%Y-%m-%d_%H:%M:%S.png"
early-exit = true
disable-notifications = true

[keybinds]
pointer = "p"
crop = "c"
brush = "b"
line = "l"
arrow = "a"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "u"
highlight = "h"

[font]
family="Noto Sans"
style="Regular"

[color-palette]
palette = [
    '#ff6b6b',
    '#8a6ede',
    '#34b45a',
    '#e7bc63',
    '#000000',
    '#25b8a4',
]

