# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 2, 4, 3 ]
linemode       = "size"

[opener]
edit = [
    { run = '${TERMCMD:-foot} ${EDITOR:-vi} "$@"', desc = "Open in $EDITOR", for = "linux" },
]
open = [
    { run = 'xdg-open "$1"', orphan = true, desc = "Open", for = "linux" },
]
image = [
    { run = 'swayimg "$1" "%d1"', orphan = true, desc = "Open in swayimg", for = "linux" },
]
play = [
    { run = 'mpv --force-window "$@"', orphan = true, for = "linux" },
    { run = 'ffprobe -i "$1"; printf "\n\nPress ENTER to continue...\n"; read _', block = true, desc = "Show ffprobe info", for = "linux" },
    { run = 'ffmpeg -i "$1" -c:v libx264 -pix_fmt yuv420p -s hd720 -c:a aac "${1%.*}_720.mp4"', block = true, desc = "Convert to 720p", for = "linux" },
    { run = 'ffmpeg -i "$1" -c:v libx264 -pix_fmt yuv420p -s hd480 -c:a aac "${1%.*}_480.mp4"', block = true, desc = "Convert to 480p", for = "linux" },
    { run = 'ffmpeg -i "$1" -c:v libx264 -pix_fmt yuv420p -an "${1%.*}_noaudio.mp4"', block = true, desc = "Remove audio", for = "linux" }
]
reveal = [
    { run = '${TERMCMD:-foot} yazi "$1"', orphan = true, desc = "Open location in new window", for = "linux" },
    { run = 'firefox "%d1"', orphan = true, desc = "Open location in firefox", for = "linux" }
]
torrent = [
    { run = 'transmission-remote -a "$1"', desc = "Download via transmission", for = "linux" },
    { run = 'transmission-remote -a --start-paused "$1"', desc = "Add torrent to transmission, do not start", for = "linux" },
]

bulk-rename = [
    { run = '${EDITOR:-vi} "%s"', block = true }
]

[open]
prepend_rules = [
    { mime = "application/bittorrent", use = [ "torrent", "reveal" ] },
    { mime = "image/*", use = [ "image", "reveal" ] },
    { mime = "text/plain", url = "bulk-rename.txt", use = ["bulk-rename"] }
]

[[plugin.prepend_fetchers]]
id   = "git"
url  = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
url  = "*/"
run  = "git"

[[plugin.prepend_previewers]]
mime = "application/bittorrent"
run  = "torrent-preview"

[[plugin.prepend_previewers]]
mime = 'audio/*'
run  = "preview-audio" 

[[plugin.prepend_preloaders]]
mime = 'audio/*'
run  = "preview-audio" 
